### ISSUE TITLE
The json data parsed by xeokit-metadata in the linux system is missing

### ISSUE THREAD

**Issue by lyluojy** [bimspot/xeokit-metadata#10]
Hello, I downloaded xeokit-metadata-linux-x64 tar.gz It is installed and used according to the tutorial. At the same time, aspnetcore-runtime-2.1.0-linux-x64 is installed. However, only half of the parsed JSON files can be displayed on the page.

**Comment by lyluojy** [comment]
Sorry, I downloaded ASP.NET Core Runtime 2.2, but it still cannot be resolved

**Comment by BalintBende** [comment]
Hello!

Which release of xeokit-metadata have you downloaded? 1.0.0 version has been upgraded to ASP.NET Core Runtime 3.1.

**Comment by lyluojy** [comment]
Hello, thanks for your reply, I have upgraded to ASP.NET Core Runtime 3.1, which solved this problem
