### ISSUE TITLE
Add support for IFC properties and property sets to metadata JSON

### ISSUE THREAD

**Issue by cemunds** [bimspot/xeokit-metadata#12]
Hi everyone,

I made a feature suggestion to enhance the support for properties and property sets in xeokit-sdk in [this](https://github.com/xeokit/xeokit-sdk/issues/498) issue and was asked by xeolabs to also open an issue here. Please see the linked issue for my suggested extension of the JSON schema.

**Comment by eriadam** [comment]
Hi @cemunds, thanks for the suggestion.

I am afraid this does not really scale. For smaller models this would be a simple solution, but for real life projects, the JSON would be hundreds of megabytes in size. This is not something most browsers (and internet connections) can handle.

I would agree with Lindsay here, that xeokit users should implement their own service to fetch properties for elements on demand.
