### ISSUE TITLE
Converting IFC to Metadata 

### ISSUE THREAD

**Issue by suryakumara** [bimspot/xeokit-metadata#14]
I've been trying to scale my IFC model into JSON metadata. I put it in the metadata folder. but executed like this.

<img width="589" alt="Screen Shot 2021-05-13 at 4 19 06 PM" src="https://user-images.githubusercontent.com/51102773/118098849-049b7600-b407-11eb-919f-bf6d02a588b3.png">

did I miss something?

**Comment by BalintBende** [comment]
Hi @suryakumara 

As i see you are using osx version of xeokit-metadata. In this case please follow the steps about using in readme.
Shortly you have to do the followings:
- download the xeokit-metadata-osx-x64.tar file
- compress it to the folder you want
- add execute mode to the file with the command `chmod +x xeokit-metadata-osx-x64/xeokit-metadata`
- you have two options here: (1) you can run it from the /xeokit-metadata-osx-x64 folder with `./xeokit-metadata` (2) or you can add a symbolic link to the file, then it can be called globally with `ln -s /absolutePath/xeokit-metadata-osx-x64/xeokit-metadata /usr/local/bin/xeokit-metadata`
- don't forget to allow security permission to the app in Security & Privacy/General

Hopefully it was helpful,
Cheers,
Balint

**Comment by suryakumara** [comment]
Hi @BalintBende Thank you for your response, I have followed all directions from you but there seems to be a problem.

<img width="839" alt="Screen Shot 2021-05-13 at 5 59 44 PM" src="https://user-images.githubusercontent.com/51102773/118110800-711d7180-b415-11eb-965b-4a79f811852d.png">
