### ISSUE TITLE
How can I extract metadata.json of ifc on the Windows system??

### ISSUE THREAD

**Issue by baoxiaozhi** [bimspot/xeokit-metadata#19]
I don't know how it works on windows system. The README.md is too simple to understand!

**Comment by BalintBende** [comment]
Hey @baoxiaozhi,

You can find all the distribution packages in the release assets. Please use the appropriate one to your system. The zip file contains dll, pdb and exe files.

Please let me know if you have problem with using it.

Cheers,
Balint

**Comment by baoxiaozhi** [comment]
> Hey @baoxiaozhi,
> 
> You can find all the distribution packages in the release assets. Please use the appropriate one to your system. The zip file contains dll, pdb and exe files, especially for windows.
> 
> Please let me know if you have problem with using it.
> 
> Cheers, Balint

Thanks for your reply. The README.md describes the usage on Linux system. How to extract the metadata of IFC file on Windows system? I want to know the specific operation command.

**Comment by BalintBende** [comment]
Hey @baoxiaozhi,

In the readme file there is just an example, how to run the command. There are various methods to run it on different systems. First you have to unpack the downloaded zipped file and you can find the executable file (.exe) in the package, that you can open and run. I think that is the easiest way.

I hope this will help.

Cheers, Balint

**Comment by baoxiaozhi** [comment]
Hey @BalintBende

I download the appropriate one  in the release assets. But when I run the executable file (.exe) in the package, the program flashes back without any error. I tried to execute this file as an administrator, but I still flashed back. Could you help me find out why？

Bao

**Comment by eriadam** [comment]
Hi Bao,

Looks like Lindsay moved the documentation. I updated the readme.


Run the command:

```
~ xeokit-metadata input.ifc output.json
```

Cheers,
Adam
