### ISSUE TITLE
Elements with null parents in JSON metadata output

### ISSUE THREAD

**Issue by xeolabs** [bimspot/xeokit-metadata#3]
After converting the [Schependomlaan IFC2x3 model](https://github.com/openBIMstandards/DataSetSchependomlaan/blob/master/Design%20model%20IFC/IFC%20Schependomlaan.ifc), the output JSON metadata contains elements with null parents - see the the  ````IfcBuildingStorey```` element in this snapshot of the JSON:

![Screenshot from 2019-12-05 18-04-21](https://user-images.githubusercontent.com/83100/70257200-24e2f200-178a-11ea-9ede-1c62768c03eb.png)

**Comment by xeolabs** [comment]
Also getting the same issue with the IFC4 [Holter Tower model](http://openifcmodel.cs.auckland.ac.nz/Model/Details/316).

**Comment by eriadam** [comment]
True. The storey should have the building as a parent, the building the site, the site the project. We'll have a look.

**Comment by wielinde** [comment]
@eriadam Do you have any information on how "production ready" `bimspot/xeokit-metadata` currently is? We would love to use it pretty soon but discovered this crucial bug yesterday.

BTW: The example in the Readme contains a JSON node of type `IfcBuildingStorey` which has a parent attribute with value `null`. Might be wrong aswell?

**Comment by eriadam** [comment]
Hello @wielinde, we are already looking into this, progress will be posted here. Should not take long to fix.
We are using this already in production, however, only for selecting building elements in the viewer, and not for displaying the structure.

**Comment by BalintBende** [comment]
Hello @xeolabs! I have fixed this bug. Only IfcProject object hasn't got parent, others has. Before release can you try it if i send you a build version? What kind of system version do you need?

**Comment by xeolabs** [comment]
Thanks @BalintBende, we appreciate the quick fix!  Linux 64 bit please.

**Comment by BalintBende** [comment]
I have attached. Please let me know if it worked.
[xeokit-metadata-linux-x64.tar.gz](https://github.com/bimspot/xeokit-metadata/files/3932144/xeokit-metadata-linux-x64.tar.gz)

**Comment by xeolabs** [comment]
@BalintBende Yip that's fixed, thanks.

**Comment by wielinde** [comment]
@BalintBende A first test was positive. Perfect! Thank you for your quick fix.
@eriadam Great to know that guys use it in production.

**Comment by eriadam** [comment]
Awesome! Coming up in version 0.0.4.
