### ISSUE TITLE
What to do with objects that have no IFC type?

### ISSUE THREAD

**Issue by xeolabs** [bimspot/xeokit-metadata#4]
Sometimes models like [Holter Tower](http://openifcmodel.cs.auckland.ac.nz/Model/Details/316) have objects that have no IFC type assigned to them. In this case, it's all the window objects.

Would it make sense to create a "dummy" meta object for each of these objects? 

That way, it would still be possible to represent them in an IFC structure tree view, where they could be within their own special "unclassified" branch of the meta object graph. Using the tree view,  we'd be able to toggle their visibility.

Use case: A BIM manager can still see those unclassified objects within a model, and be able to indicate that somebody should fix them (eg. via BCF).

I tried automatically handling such objects within xeokit, but it slows down loading due to all the book-keeping involved. Would be nicer to handle them upstream if possible.

**Comment by eriadam** [comment]
We just had a look. It seems, this has to do with elements not being directly in the structure of storeys, etc, but are referenced through `IFCRELCONTAINEDINSPATIALSTRUCTURE` or other `IfcRelConnects` references. Curtain walls are a good example.

We'll create some example files, test some more and get back to you.

**Comment by BalintBende** [comment]
Hey @xeolabs! I have fixed this bug and tested with some model, also Holter Tower, but you can check simply with my new test model called Curtainwall.ifc. This model represents the case when building elements for example IfcPlates are part of the curtain wall system.
[Curtainwall.ifc.zip](https://github.com/bimspot/xeokit-metadata/files/3955555/Curtainwall.ifc.zip)

**Comment by xeolabs** [comment]
Thanks @BalintBende! 

I actually thought this was a bug in the original IFC models themselves - didn't realise it was a case of fixing xeokit-metadata as such. 

Would I be able to get a Linux 64-bit build to test with?

**Comment by BalintBende** [comment]
Yes of course, you can find in attachment.
[xeokit-metadata-linux-x64.tar.gz](https://github.com/bimspot/xeokit-metadata/files/3955642/xeokit-metadata-linux-x64.tar.gz)

 Thank you for the testing. Please share with your remarks, then I will release it.

**Comment by xeolabs** [comment]
Morning @BalintBende, looks like that tar.gz is empty

**Comment by BalintBende** [comment]
[xeokit-metadata-linux-x64.tar.gz](https://github.com/bimspot/xeokit-metadata/files/3960217/xeokit-metadata-linux-x64.tar.gz)
sorry, try again with this one.

**Comment by xeolabs** [comment]
Not sure if it's fixed, at least for Holter Tower - this is what I'm getting when loading the Curtainwall:

![Screenshot from 2019-12-13 11-37-13](https://user-images.githubusercontent.com/83100/70794732-a516e200-1d9e-11ea-8a5f-48cd1a1ecdd8.png)

And this is what I'm getting with Holter Tower:

![Screenshot from 2019-12-13 11-48-37](https://user-images.githubusercontent.com/83100/70794754-b19b3a80-1d9e-11ea-9270-f9a5aa3064da.png)

Note that I've configured XKTLoaderPlugin to not load objects that have no IFC type, using this new ````excludeUnclassifiedObjects```` option: 

````javascript
    const model = xktLoader.load({
        id: "myModel",
        src: "./models/xkt/HolterTower/HolterTower.xkt",
        metaModelSrc: "./metaModels/HolterTower/HolterTower.json", 
        excludeUnclassifiedObjects: true,
        edges: true
    });
````

When I set ````excludeUnclassifiedObjects```` false, the windows on the Holter tower reappear:

![Screenshot from 2019-12-13 11-52-13](https://user-images.githubusercontent.com/83100/70795067-4dc54180-1d9f-11ea-8f84-fa0699410d36.png)

**Comment by BalintBende** [comment]
Can you please send me a sample object GUID which has not IFC type in this model? In theory every object must have an exact type. I suspect that some types are out of the filter.

**Comment by xeolabs** [comment]
Try this one, in the Holter Tower model: "1fBfl1vqn5guiPIwj$uJY7"

![Screenshot from 2019-12-13 14-55-45](https://user-images.githubusercontent.com/83100/70805374-0d72bd00-1db9-11ea-8fb8-e33db3cfee80.png)

**Comment by BalintBende** [comment]
In my generated output json this object is there:
{
      "id": "1fBfl1vqn5guiPIwj$uJY7",
      "name": "Panel M-09",
      "type": "IfcPlate",
      "parent": "2_ZJ1wSVjC3PIQbT7lY_cB"
    },

Is something went wrong?

**Comment by xeolabs** [comment]
Sorry, I just realized gave you the ID of the **parent** of the element. 

Try this ID - this is the ID of one of the windows, which is missing in the JSON: 3BmncaCsL6u9VV$Gsk1rcx

This is the JSON I get after testing with the latest build:

file:/home/lindsay/xeolabs/xeokit/xeokit-october/xeokit-sdk/examples/metaModels/HolterTower/HolterTower.json

**Comment by xeolabs** [comment]
This is the JSON I created using the latest build: [20181220Holter_Tower_10.json.zip](https://github.com/bimspot/xeokit-metadata/files/3961204/20181220Holter_Tower_10.json.zip)

**Comment by BalintBende** [comment]
Its not similar with mine. I have a rebuild.
[xeokit-metadata-linux-x64.tar.gz](https://github.com/bimspot/xeokit-metadata/files/3961300/xeokit-metadata-linux-x64.tar.gz)
I hope this will work.

**Comment by xeolabs** [comment]
Thanks, that's fixed it - note how the windows now get XKTLoaderPlugin's default appearance for IfcWindow types: ![Screenshot from 2019-12-13 15-56-39](https://user-images.githubusercontent.com/83100/70809033-444cd100-1dc1-11ea-8c02-ebd8dd7d10f6.png)

I also updated the metadata for the [Holter Tower example](https://xeokit.github.io/xeokit-sdk/examples/#BIMOffline_XKT_HolterTower) - note how all objects now show/hide when checking/unchecking the root checkbox in the tree view.

Cheers!
