### ISSUE TITLE
How to install xeokit-metada in Windows 

### ISSUE THREAD

**Issue by ChetouaniZakaria** [bimspot/xeokit-metadata#8]
I tried to build xeokit.sln with visual studio
![Capture](https://user-images.githubusercontent.com/48649658/80957256-1b29ed00-8e03-11ea-83d7-ce54d90fd3b7.PNG)

**Comment by BalintBende** [comment]
Dear @ChetouaniZakaria 

xeokit-metadata is built with .NET Core 2.2, please install this framework for building the project.
https://dotnet.microsoft.com/download/dotnet-core

I hope this helps.

**Comment by ChetouaniZakaria** [comment]
thank you for your response.
I've already installed this package, but it doesn't work, I think because this version of .net is deprecated.

**Comment by BalintBende** [comment]
Hello @ChetouaniZakaria 

We are planning to update to .NET Core 3.1 in the near future.

**Comment by eriadam** [comment]
Closing this as 3.1 was released with version 1.0.0. https://github.com/bimspot/xeokit-metadata/releases/tag/1.0.0
