### ISSUE TITLE
Command run error on linux

### ISSUE THREAD

**Issue by cander0815** [bimspot/xeokit-metadata#9]
Hello, After installing according to the instructions in the document, the operation prompts this error, how can I solve it?
```

A fatal error occurred, the required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/root/xeokit-metadata-linux-x64/].
If this is a framework-dependent application, install the runtime in the default location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.

```

**Comment by eriadam** [comment]
Hello! Thanks for getting in touch. It seems there is something wrong with your dotnet installation. Please [refer to the docs for installation](https://docs.microsoft.com/en-us/dotnet/core/install/linux). Currently we are on 2.2, but updating to the latest one version soon.

Alternatively, you may be interested in the full converter pipeline: https://github.com/bimspot/xeokit-converter
